name: Update Base URL

on:
  repository_dispatch:
    types: [created]
  create:
    branches: [master]

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Update base_url
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          sed -i "s/^base_url = .*$/base_url = \"\/$REPO_NAME\"/" config.toml

      - name: Commit and push changes
        run: |
          git add config.toml
          git commit -m "Update base_url to match repository name"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}